"""10d

Revision ID: 1378d374d7b2
Revises: d5819272c39e
Create Date: 2016-07-21 09:38:22.931496

"""

# revision identifiers, used by Alembic.
revision = '1378d374d7b2'
down_revision = 'd5819272c39e'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('avatar_hash', sa.String(length=32), nullable=True))
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'avatar_hash')
    ### end Alembic commands ###
